kind: pipeline
name: default

steps:
  - name: app-test
    image: bluerain/cicr:build
    pull: true
    commands:
      - shards --production
      - KEMAL_ENV=test crystal spec

  - name: app-build
    image: bluerain/cicr:build
    pull: true
    commands:
      - shards build cicr --release --progress --production

  - name: image-build
    image: docker
    commands:
      - docker build . -t bluerain/cicr
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    when:
      branch:
        - master
      event:
        - push
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
